
### Get token from keycloak
# curl
#  -d "client_id=user-service-api"
#  -d "client_secret=39dLCdPxu31vv3jxeUPRlRQYqmgrOyE9"
#  -d "username=lsegura"
#  -d "password=lsegura"
#  -d "grant_type=password"
#  "http://localhost:8180/realms/expense-tracker/protocol/openid-connect/token"
POST http://localhost:8180/realms/expense-tracker/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = user-service-api &
client_secret = 39dLCdPxu31vv3jxeUPRlRQYqmgrOyE9 &
username = lsegura &
password = lsegura &
grant_type = password
###


### Post User
# curl -X POST http://localhost:8080/user-service/api/users
#  -H "Content-Type: application/json"
#  -H "Authorization: Bearer <token>"
#  -d '{
#    "username": "johndoe",
#    "email": "john@example.com",
#    "password": "secret",
#    "fullName": "John Doe"
#  }'
POST http://localhost:8080/user-service/api/users
Authorization: Bearer <token>
Content-Type: application/json

{
  "username": "jDoe",
  "email": "john@dev2ever.com",
  "password": "123",
  "fullName": "John Doe"
}

### Get all users
# curl -X GET http://localhost:8080/user-service/api/users
#  -H "Accept: application/json"
#  -H "Authorization: Bearer <token>"
GET http://localhost:8080/user-service/api/users
Accept: application/json
Authorization: Bearer <token>

###


### Get user by ID
# curl -X GET http://localhost:8080/user-service/api/users/1
#  -H "Accept: application/json"
#  -H "Authorization: Bearer <token>"
GET http://localhost:8080/user-service/api/users/1
Accept: application/json
Authorization: Bearer <token>

###

### Delete user by ID
# curl -X DELETE http://localhost:8080/user-service/api/users/1
#  -H "Authorization: Bearer <token>"
DELETE http://localhost:8080/user-service/api/users/1
Authorization: Bearer <token>
###



### Update user by ID
# curl -X PUT http://localhost:8080/user-service/api/users/1
#  -H "Content-Type: application/json"
#  -H "Authorization: Bearer <token>"
#  -d '{
#    "username": "johndoe",
#    "email": "john@example.com",
#    "password": "secret",
#    "fullName": "John Doe"
#  }'
PUT http://localhost:8080/user-service/api/users/1
Authorization: Bearer <token>
Content-Type: application/json

{
  "username": "jDoe",
  "email": "john@dev2ever.com",
  "password": "123",
  "fullName": "John Doee"
}

###




